[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader_api = "0.11"
uart_16550 = "0.3.0"
noto-sans-mono-bitmap = "0.2.0"
x86_64 = "0.14.2"